name: "Setup Rust development environment"
description: "Setup Rust development environment for GitHub Actions"

inputs:
  apt-packages:
    description: "Optional apt packages to install before building"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup | Install apt packages
      if: inputs.apt-packages != ''
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}

    - name: Setup | Cache cargo store
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-cargo-

    - name: Setup | Fetch cargo dependencies
      shell: bash
      run: cargo fetch --locked
