[tools]
node = "22.14.0"
"npm:pnpm" = "10.10.0"

[env]
_.file = ".env"

[tasks.start-o11y]
run = "docker run --rm -p 16686:16686 -p 4318:4318 jaegertracing/all-in-one:latest"

[settings]
experimental = true
