allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAge: 1440

packages:
  - .
  - packages/*

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
