name = "mcc-room-manager"
compatibility_date = "2024-06-20"

[[d1_databases]]
binding = "DB"
database_name = "mcc-room-manager"
database_id = "ad2e933a-ebc8-440a-aa3a-33f3d18b9794"
migrations_dir = "./drizzle"
