[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
pasori = { path = "../pasori" }
tokio = { version = "1.44.2", features = [
  "rt",
  "rt-multi-thread",
  "net",
  "sync",
  "macros",
] }
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
