[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
pasori = { path = "../pasori" }
tokio = { version = "1.44.2", features = [
  "rt",
  "rt-multi-thread",
  "net",
  "sync",
  "macros",
  "time",
] }
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
reqwest = { version = "0.12.15", default-features = false, features = [
  "json",
  "rustls-tls",
] }
serde = { version = "1.0.219", features = ["derive"] }
rodio = { version = "0.20.1", default-features = false, features = ["symphonia-wav"] }
