name = "room-manager"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[triggers]
# 毎日20時15分に実行する
# GMTでのみ指定可能なため、日本時間では+9時間を引く
crons = ["15 11 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "room-manager"
database_id = "446d1a4f-12a2-47a5-a262-be61f14b104a"
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "KV"
id = "d6296b0fc1ff45849d857cbc39b9b656"

[env.production.vars]
DISCORD_PUBLIC_KEY = "ec800ecdaa5ff680bb9e180300fa7dd157a6d1ae4b3d3640070a35f58f31b09f"
DISCORD_GUILD_ID = "882598552780562462"
DISCORD_CHANNEL_ID = "923521135734325288"
DISCORD_ROOM_COMMAND_ID = "1365551182323384322"
DISCORD_ROOM_ADMIN_COMMAND_ID = "1365551182323384323"
