name = "room-manager"
compatibility_date = "2024-06-20"

[triggers]
# 毎日20時15分に実行する
# GMTでのみ指定可能なため、日本時間では+9時間を引く
crons = ["15 11 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "room-manager"
database_id = "446d1a4f-12a2-47a5-a262-be61f14b104a"
migrations_dir = "./drizzle"
