
name: Build
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_node:
    name: Build (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Build
        run: pnpm run -r build

  build_rust:
    name: Build (Rust)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Build
        run: cross build --release --locked
