name: Check
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Build
        run: pnpm run -r build

  build_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Build
        run: cross build --release --locked

  typecheck_node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Typecheck
        run: pnpm run -r typecheck

  lint_node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Lint
        run: pnpm run -r lint

  lint_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Lint (Rust)
        run: cross clippy --all-targets --all-features -- -D warnings

  format_node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Format
        run: pnpm run -r format:check

  format_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Format
        run: cargo fmt --all -- --check

  test_node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Test
        run: pnpm run -r test

  test_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Test
        run: cross test --all-targets --all-features
