name: Check
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  typecheck_node:
    name: Typecheck (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Typecheck
        run: pnpm run -r typecheck

  lint_node:
    name: Lint (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Lint
        run: pnpm run -r lint

  lint_rust:
    name: Lint (Rust)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Lint (Rust)
        run: cross clippy --all-targets --all-features -- -D warnings

  format_node:
    name: Format (Node.js)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Run | Format
        run: pnpm run -r format:check

  format_rust:
    name: Format (Rust)
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Format
        run: cargo fmt --all -- --check
