name: Release please
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Setup | Get bot token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.MCC_BOT_APP_ID }}
          private-key: ${{ secrets.MCC_BOT_PRIVATE_KEY }}

      - name: Run | Release please
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}

  release:
    needs: [release-please]
    uses: ./.github/workflows/release.yml
    if: needs.release-please.outputs.release_created == 'true'
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
