name: Release
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup | Rust development environment
        uses: ./.github/actions/setup-rust

      - name: Run | Build
        run: cross build --release --locked

      - name: Run | Compress
        run: |
          tar czvf \
            room-manager-aarch64-unknown-linux-gnu.tar.gz \
            target/aarch64-unknown-linux-gnu/release/room-manager
            README.md

      - name: Run | Upload
        run: gh release upload v${{ inputs.version }} room-manager-aarch64-unknown-linux-gnu.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
