name: Release please
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup | Node.js development environment
        uses: ./.github/actions/setup-node

      - name: Setup | Get bot token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.MCC_BOT_APP_ID }}
          private-key: ${{ secrets.MCC_BOT_PRIVATE_KEY }}

      - name: Run | Release please
        id: release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # 4.2.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node
          skip-labeling: true

  release:
    needs: [release-please]
    uses: ./.github/workflows/release.yml
    if: needs.release-please.outputs.release_created == 'true'
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
